# compose file for local testing of 'full-stack'

version: "3.9"

services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data

  etl:
    build:
      context: ./etl/
      dockerfile: dockerfiles/dev.Dockerfile
    container_name: etl
    ports:
      - 8080:8080
    env_file:
      - ./etl/envs/.env.dev
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: global_news_feed_db
    depends_on:
      - db
    links:
      - db:db

  backend:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./backend/
        target: /mnt/
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: global_news_feed_db
    depends_on:
      - db
    links:
      - db:db

volumes:
  db:
    driver: local