# docker-compose for local testing of the database
# environment used during the ETL processes.
#
# A PostgreSQL database service is created 

version: "3.9"

services:

  # This is the database service for the ETL process
  db:
    image: postgres:14.1-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  # This uses the ETL package code to run the database
  # set-up script
  etl:
    restart: always
    build:
      context: ./
      dockerfile: db-local-setup.Dockerfile
      args:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_HOST: db
        DB_PORT: 5432
        DB_NAME: global_news_feed_db
    container_name: etl-code
    depends_on:
      - db
    links:
      - db:db

volumes:
  db:
    driver: local