name: Cron Task

on:
  schedule: 
    - cron: * * * * *

jobs:
  run:
    name: Run Task
    runs-on: ubuntu-latest

    steps:

    - name: Pull Image
      run: echo "Pull"

    - name: Execute Task
      run: echo "Execute"