name: ETL-Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r etl/requirements.txt

      - name: Run unit tests
              run: python -m pytest --import-mode=append etl/tests/